'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle:   Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal: Pn=n(3n-1)/2  1, 5, 12, 22, 35, ...
Hexagonal:  Hn=n(2n-1)    1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

Notes:
Given an inverse check method for Hex and Penta numbers, we can just start with T286 and work up from there. 
'''
import time
import math
def main():
	tc = time.clock()
	n = 286
	t = n*(n+1)/2
	while(not isPenta(t) or not isHex(t)):
		n += 1
		t = n*(n+1)/2

	print "Answer: %d" % t
	print "Time Taken: %0.3f seconds" % (time.clock()-tc)


#The inverse of the Penta Number function, easy check if a number is penta. 
def isPenta(val):
	f = (math.sqrt(1 + 24*val) + 1) / 6
	return f == int(f)

def isHex(val):
	f = (math.sqrt(2*val+0.25) + 0.5) / 2
	return f == int(f)

if __name__ == '__main__':
	main()
